TargetServer.class: TargetServer.java DoActionServlet.java LoginServlet.java ViewPageServlet.java
	javac -cp "./lib/*:." TargetServer.java DoActionServlet.java LoginServlet.java ViewPageServlet.java

clean:
	rm -f *.class

